require('proof')(1, (okay) => {
    const Destructible = require('destructible')
    const destructible = new Destructible('dispatcher')
    const Dispatcher = require('../dispatcher')
    const dispatcher = new Dispatcher(destructible, null)
    destructible.destroy()
    dispatcher.fromParent({})
    dispatcher.fromParent({}, { destroy: () => {} })
    okay('ignored')
})
