#!/bin/sh

set -e

echo ""

(proof run t/*.t.js | tee .proof.out | proof progress) \
    || (proof errors < .proof.out) \
    || exit 1

if [ "$TRAVIS" = "true" ]; then
  for i in {1..25}; do node t/listener.t.js || echo bummer; done
  echo ""
  echo "running with coverage"
  t/cover
  istanbul report --format text
  echo ""

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | coveralls) > /dev/null 2>&1
fi

echo ""
