#!/bin/sh

set -e

echo ""

if [ "$TRAVIS" = "true" ]; then
  bash -c 'for i in {1..5}; do rm -f t/socket && node t/olio.bin.t.js || echo bummer; done'
fi

(proof run t/*.t.js | tee .proof.out | proof progress) \
    || (proof errors < .proof.out) \
    || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  istanbul report --format text
  echo ""

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | coveralls) > /dev/null 2>&1
fi

echo ""
